version: '3'
services:
  app:
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
    volumes:
      - ./static:/app/static

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"